#!/usr/bin/env bash
# ZenDNN A/B benchmark: evaluate the SAME RAG pipeline with a baseline llama.cpp
# backend, then with the ZenDNN build, then emit a comparison report.
#
#   ./run_ab.sh
#
# A/B swaps BOTH the chat AND the embed server together per job (by overriding
# their images), so the report compares the whole inference path under each
# backend (query embedded + answer generated by the same backend).
#
# Jobs run STRICTLY SEQUENTIALLY (one backend at a time) so they never compete
# for CPU — clean, comparable numbers. Both images are built from public source
# by `make build-llama` (same commit, fair A/B). Requires the stack up and docs
# ingested first:  docker compose up -d  &&  make ingest
set -euo pipefail
cd "$(dirname "$0")"

DC_BASE="docker compose"
DC_AB="docker compose -f docker-compose.yml -f docker-compose.ab.yml"

env_get() { local v; v="$(grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2-)"; [ -z "$v" ] && echo "$2" || echo "$v"; }
log() { echo "[run_ab] $*"; }
die() { echo "[run_ab] ERROR: $*" >&2; exit 1; }

[ -f .env ] || die "no .env — run ./setup.sh first"
CHAT_PORT="$(env_get CHAT_PORT 8081)"
EMBED_PORT="$(env_get EMBED_PORT 8082)"
ALLM_PORT="$(env_get ALLM_PORT 3001)"
LITELLM_PORT="$(env_get LITELLM_PORT 4000)"
PUSHGW_PORT="$(env_get PUSHGW_PORT 9091)"
SLUG="$(env_get SLUG nq-bench)"
ALLM_KEY="$(env_get ALLM_KEY '')"
CHAT_MODEL_PATH="$(env_get CHAT_MODEL_PATH '')"

# A/B knobs (override in .env). Backends are now images built from public source.
AB_BASELINE_IMAGE="$(env_get LLAMA_BASELINE_IMAGE "nqrag-llama:baseline")"
AB_ZENDNN_IMAGE="$(env_get LLAMA_ZENDNN_IMAGE "nqrag-llama:zendnn")"
AB_ZENDNN_ALGO="$(env_get AB_ZENDNN_ALGO "1")"
# Fixed-decode mode: set AB_FIXED_DECODE=<N> (in .env or env) to force EVERY query
# to emit exactly N decode tokens on BOTH backends (ignore_eos + n_predict=N),
# so prefill+decode work is identical and latency is directly comparable. Empty =
# off (natural generation, quality-meaningful). Quality judging is skipped when on.
AB_FIXED_DECODE="$(env_get AB_FIXED_DECODE "")"
LITELLM_YAML="conf/litellm.yaml"
JOB_A="${JOB_A:-baseline}"
JOB_B="${JOB_B:-zendnn}"

# ── preconditions ────────────────────────────────────────────────────────────
[ -n "$ALLM_KEY" ] || die "ALLM_KEY empty — set it in .env (or run docker compose up so the seed service configures AnythingLLM)"
[ -n "$CHAT_MODEL_PATH" ] || die "CHAT_MODEL_PATH must point at a local GGUF for the A/B (set it in .env)"

# Ensure both backend images exist (built from public source, same commit).
image_exists() { docker image inspect "$1" >/dev/null 2>&1; }
if ! image_exists "$AB_BASELINE_IMAGE" || ! image_exists "$AB_ZENDNN_IMAGE"; then
    log "building llama.cpp images ($AB_BASELINE_IMAGE + $AB_ZENDNN_IMAGE) from source ..."
    make build-llama || die "failed to build llama.cpp images (see docker/llama/Dockerfile)"
fi

log "ensuring base services are up (litellm/prometheus/anythingllm) ..."
$DC_BASE up -d litellm prometheus anythingllm >/dev/null
[ -f data/ingest_metadata.json ] || die "no ingested data — run: make ingest"

wait_for() {  # name url tries
    echo -n "[run_ab] waiting for $1 "
    for _ in $(seq 1 "${3:-120}"); do
        if curl -fsS -m 5 "$2" >/dev/null 2>&1; then echo " up"; return 0; fi
        echo -n "."; sleep 5
    done
    echo " TIMEOUT"; return 1
}

# ── fixed-decode mode ────────────────────────────────────────────────────────
# Point AnythingLLM at the `chat-model-bench` LiteLLM model (ignore_eos +
# n_predict=N) so both backends emit exactly N decode tokens. Restored on exit.
DOJUDGE_ARGS=""
BENCH_ACTIVE=0
restore_stack() {
    [ "$BENCH_ACTIVE" = "1" ] || return 0
    log "restoring stack after fixed-decode run (model→chat-model, litellm.yaml) ..."
    [ -f "$LITELLM_YAML.abbak" ] && mv -f "$LITELLM_YAML.abbak" "$LITELLM_YAML"
    CHAT_MODEL_NAME=chat-model $DC_BASE up -d --force-recreate --no-deps anythingllm >/dev/null 2>&1 || true
    $DC_BASE restart litellm >/dev/null 2>&1 || true
    BENCH_ACTIVE=0
}
trap restore_stack EXIT INT TERM

enable_fixed_decode() {  # N
    local n="$1"
    case "$n" in ''|*[!0-9]*) die "AB_FIXED_DECODE must be a positive integer, got '$n'";; esac
    [ "$n" -gt 0 ] || die "AB_FIXED_DECODE must be > 0"
    log "════ fixed-decode mode ON: forcing exactly $n decode tokens/query on both backends ════"
    cp -f "$LITELLM_YAML" "$LITELLM_YAML.abbak"
    BENCH_ACTIVE=1
    # rewrite the (integer) n_predict in the chat-model-bench block
    sed -i -E "s/^([[:space:]]*n_predict:[[:space:]]*)[0-9]+/\1$n/" "$LITELLM_YAML"
    $DC_BASE restart litellm >/dev/null
    wait_for "litellm" "http://localhost:${LITELLM_PORT}/health/readiness" 30 || true
    # recreate AnythingLLM so it picks up GENERIC_OPEN_AI_MODEL_PREF=chat-model-bench
    CHAT_MODEL_NAME=chat-model-bench $DC_BASE up -d --force-recreate --no-deps anythingllm >/dev/null
    wait_for "anythingllm" "http://localhost:${ALLM_PORT}/api/ping" 60
    DOJUDGE_ARGS="-e DO_JUDGE=0"   # judging truncated answers is meaningless
}

# Push the current backend name to Pushgateway so Grafana can display it.
push_backend() {  # name   (e.g. "baseline", "zendnn", "idle")
    printf 'ab_backend_active{backend="%s"} 1\n' "$1" \
        | curl -fsS -m 5 --data-binary @- \
          "http://localhost:${PUSHGW_PORT}/metrics/job/ab_bench" 2>/dev/null || true
}

# Verify the prompt cache is actually disabled for the freshly-swapped backend
# BEFORE spending ~15 min on the eval. Sends the SAME question twice through the
# real eval path (AnythingLLM stream-chat) and compares the chat server's
# prompt_tokens_total delta. With cache_prompt:false honored end-to-end both
# deltas are ~equal (full reprocess each time). If the 2nd delta collapses, the
# slot KV is being reused → the per-query prefill numbers would be inflated and
# prompt_tokens would diverge from the other job (the bug we are guarding).
chat_ptok() { curl -fsS -m 10 "http://localhost:${CHAT_PORT}/metrics" 2>/dev/null \
    | awk '/^llamacpp:prompt_tokens_total/{print $2}'; }
verify_cache_disabled() {  # job
    local job="$1" q='When was the last time anyone was on the moon?' b1 a1 b2 a2 d1 d2
    # Use a FRESH AnythingLLM session per call so neither request carries chat
    # history — both then send an identical prompt to llama-server, isolating the
    # server-side KV-cache-reuse signal we're probing (history carryover would
    # otherwise change call 2's prompt and confound the delta comparison).
    local s1="cacheprobe-${job}-$$-a" s2="cacheprobe-${job}-$$-b"
    b1="$(chat_ptok)"
    curl -fsS -m 600 "http://localhost:${ALLM_PORT}/api/v1/workspace/${SLUG}/stream-chat" \
        -H "Authorization: Bearer ${ALLM_KEY}" -H 'Content-Type: application/json' \
        -d "{\"message\":\"$q\",\"mode\":\"query\",\"sessionId\":\"$s1\"}" >/dev/null 2>&1
    a1="$(chat_ptok)"
    b2="$(chat_ptok)"
    curl -fsS -m 600 "http://localhost:${ALLM_PORT}/api/v1/workspace/${SLUG}/stream-chat" \
        -H "Authorization: Bearer ${ALLM_KEY}" -H 'Content-Type: application/json' \
        -d "{\"message\":\"$q\",\"mode\":\"query\",\"sessionId\":\"$s2\"}" >/dev/null 2>&1
    a2="$(chat_ptok)"
    d1=$(awk "BEGIN{print $a1-$b1}"); d2=$(awk "BEGIN{print $a2-$b2}")
    # ratio of the smaller to larger delta; ~1.0 = cache disabled, ~0 = reuse
    local ratio; ratio=$(awk "BEGIN{lo=($d1<$d2?$d1:$d2); hi=($d1>$d2?$d1:$d2); print (hi>0)?lo/hi:0}")
    log "cache-probe '$job': prompt_tokens delta call1=$d1 call2=$d2 (ratio=$ratio)"
    awk "BEGIN{exit !($ratio>0.9)}" \
        || log "⚠️  WARNING: prompt cache appears ACTIVE for '$job' (2nd request reprocessed far fewer tokens). prompt_tokens/prefill numbers may be inflated and will NOT match the other job."
}

run_job() {  # job image algo
    local job="$1" image="$2" algo="$3"
    log "════ job '$job': swapping BOTH chat+embed backends to image=$image (algo=${algo:-unset}) ════"
    # Recreate chat AND embed together so the query is embedded and answered by
    # the same backend. --no-deps leaves litellm/anythingllm untouched.
    CHAT_IMAGE="$image" EMBED_IMAGE="$image" \
        ZENDNNL_MATMUL_ALGO="$algo" AB_JOB="$job" \
        $DC_AB up -d --force-recreate --no-deps llama-chat llama-embed
    wait_for "chat ($job)" "http://localhost:${CHAT_PORT}/health" 120 \
        || { $DC_AB logs --tail 40 llama-chat; die "chat server ($job) did not come up"; }
    wait_for "embed ($job)" "http://localhost:${EMBED_PORT}/health" 120 \
        || { $DC_AB logs --tail 40 llama-embed; die "embed server ($job) did not come up"; }
    docker logs nqrag-llama-chat  2>&1 | grep -iE 'zendnn|backend' | head -3 || true
    docker logs nqrag-llama-embed 2>&1 | grep -iE 'zendnn|backend' | head -3 || true
    verify_cache_disabled "$job"
    push_backend "$job"
    log "evaluating job '$job' ..."
    $DC_BASE run --rm -e JOB="$job" $DOJUDGE_ARGS harness python evaluate.py
    push_backend "idle"
}

[ -n "$AB_FIXED_DECODE" ] && enable_fixed_decode "$AB_FIXED_DECODE"

run_job "$JOB_A" "$AB_BASELINE_IMAGE" ""
run_job "$JOB_B" "$AB_ZENDNN_IMAGE"   "$AB_ZENDNN_ALGO"

log "generating comparison report ..."
$DC_BASE run --rm -e JOB_A="$JOB_A" -e JOB_B="$JOB_B" harness python report_ab.py

log "✅ done. Report: data/results/report_ab.md (+ report_ab.json)"
