SERVER_PORT=${ALLM_PORT}
STORAGE_DIR=/app/server/storage
VECTOR_DB=lancedb
DISABLE_TELEMETRY=true

# LLM via LiteLLM (Generic OpenAI provider)
LLM_PROVIDER=generic-openai
GENERIC_OPEN_AI_BASE_PATH=http://127.0.0.1:${LITELLM_PORT}/v1
GENERIC_OPEN_AI_API_KEY=${LITELLM_MASTER_KEY}
GENERIC_OPEN_AI_MODEL_PREF=chat-model
GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT=${CHAT_CTX}

# Embedder via LiteLLM (Generic OpenAI embedder)
EMBEDDING_ENGINE=generic-openai
EMBEDDING_BASE_PATH=http://127.0.0.1:${LITELLM_PORT}/v1
GENERIC_OPEN_AI_EMBEDDING_API_KEY=${LITELLM_MASTER_KEY}
EMBEDDING_MODEL_PREF=embed-model
EMBEDDING_MODEL_MAX_CHUNK_LENGTH=${CHAT_CTX}
